name: Scripta workflow

on:
  push:
    branches: ["main"]
  

permissions:
  contents: write
  deployments: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout Scripta
        uses: actions/checkout@v4
        with:
          repository: rossoc/Scripta
          path: ./scripta
      - name: Compile Scripta
        run: |
            cd scripta && cargo build
      - name: Build HTML
        run: |
            ./scripta/target/debug/Scripta
      - name: Show changes for debugging
        run: |
          git status
          git diff
      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site
      - name: Setup Pages
        uses: actions/configure-pages@v4

  deploy:
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v4
